#pragma once

#include "tree.c"

#include <string.h>

extern Symbols queue;

/* Sweeps through the symbol tree & storage to find all related symbols and
   outputs the resulting typst-compatible expression to stdout */
#define PRINT_RESULTS(addr_of, arr)                                            \
	do {                                                                       \
		for(size_t i = 0; i < (arr).len; i++) {                                \
			struct Symbol* sym = addr_of(arr).ptr[i];                          \
                                                                               \
			/* Write readout header */                                         \
			fprintf(                                                           \
				stderr, "SYMBOL:\n\tKey: %.*s\n", (int) sym->key.len,          \
				sym->key.str                                                   \
			);                                                                 \
			fprintf(stderr, "\tType: %s\n", show_tokentype(sym->type));        \
			fprintf(stderr, "\tChildren: ");                                   \
                                                                               \
			/* Write children to readout */                                    \
			for(size_t j = 0; j < sym->children.len; j++) {                    \
				StringView child_key = sym->children.ptr[j]->key;              \
                                                                               \
				fprintf(stderr, "%.*s, ", (int) child_key.len, child_key.str); \
			}                                                                  \
                                                                               \
			/* Finish writing readout */                                       \
			fprintf(stderr, "\n");                                             \
		}                                                                      \
	} while(0);

/* Runs through all symbols in the symbols tree below 'root' and pushes creates
   a deduplicated list of correctly ordered definitions in 'queue' */
void make_queue(struct Symbol* root);

/* Dumps final results of the evaluated expression to stdout; takes the queue
   generated by 'make_queue()' */
void pretty_print(Symbols queue);

#if __INCLUDE_LEVEL__ == 0 /////////////////////////////////////////////////////

Symbols queue;

void make_queue(struct Symbol* root) {
	ArrayAdd(queue, root);

	for(size_t i = 0; i < queue.len; i++) {
		struct Symbol* iter = queue.ptr[i];

		for(size_t j = 0; j < iter->children.len; j++) {
			struct Symbol* jter = iter->children.ptr[j];

			if(jter->type != IDENT) continue;

			for(size_t k = 0; k < queue.len; k++) {
				struct Symbol* kter = queue.ptr[k];

				if(jter == kter) goto skip;
			}

			ArrayAdd(queue, jter);

		skip:
			continue;
		}
	}
}

void pretty_print(Symbols queue) {
	for(size_t i = 1; i < queue.len; i++) {
		struct Symbol* iter = queue.ptr[i];

		fprintf(stdout, "%.*s = ", (int) iter->key.len, iter->key.str);

		for(size_t j = 0; j < iter->children.len; j++) {
			struct Symbol* jter = iter->children.ptr[j];

			fprintf(stdout, "%.*s", (int) jter->key.len, jter->key.str);
		}

		if(iter->children.len < 2) {
			// Skip definition if symbol is primitive
			fprintf(stdout, "\n");
		} else {
			fprintf(stdout, " = \n");
		}
	}
}

#endif
